/* 
**  mod_file_directive.c -- Apache sample file_directive module
**  [Autogenerated via ``apxs -n file_directive -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_file_directive.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /file_directive in as follows:
**
**    #   httpd.conf
**    LoadModule file_directive_module modules/mod_file_directive.so
**    <IfFileExists /path/to/some.conf>
**        Include /pth/to/some.conf
**    </IfFileExists>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_log.h"
#include "ap_config.h"

static int is_file_exists(cmd_parms *cmd, const char *path)
{
    apr_finfo_t finfo;
    const char *fname;

    fname = ap_server_root_relative(cmd->pool, path);

    if(apr_stat(&finfo, fname, APR_FINFO_TYPE, cmd->pool) == APR_SUCCESS) {
        ap_log_perror(APLOG_MARK, APLOG_STARTUP, 0,
                      cmd->pool,
                      "File exits: %s", fname);
        return true;
    }
    else {
        ap_log_perror(APLOG_MARK, APLOG_STARTUP, 0,
                      cmd->pool,
                      "File not exits: %s", fname);
        return false;
    }
}

static const char *start_if_file_exists(cmd_parms *cmd, void *dummy, const char *arg)
{
    const char *endp;
    int exists;
    int not = 0;

    endp = ap_strrchr_c(arg, '>');
    if (endp == NULL) {
        return unclosed_directive(cmd);
    }

    arg = apr_pstrndup(cmd->pool, arg, endp - arg);

    if (arg[0] == '!') {
        not = 1;
        arg++;
    }

    exists = is_file_exists(cmd, arg);
    if((!not && exists) || (not && !exists)) {
        ap_directive_t *parent = NULL;
        ap_directive_t *current = NULL;
        const char *retval;

        retval = ap_build_cont_config(cmd->pool, cmd->temp_pool, cmd,
                                      &current, &parent, "<IfFileExists");
        *(ap_directive_t **)dummy = current;
        return retval;
    }
    else {
        *(ap_directive_t **)dummy = NULL;
        return ap_soak_end_container(cmd, "<IfFileExists");
    }
}

static const command_rec file_directive_cmds[] =
{
    AP_INIT_TAKE1("<IfFileExists", start_if_file_exists, NULL, EXEC_ON_READ | RSRC_CONF,
                  "Container for directives based on existance of specific file"),
    NULL,
};

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA file_directive_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    file_directive_cmds,  /* table of config file commands       */
    NULL,  /* register hooks                      */
};

